#!/usr/bin/env python3
"""
Generate Figure: Random-flip ablation (BRD vs flip rate).

Reads pre-computed results from results/ablation_random_flip.csv
(generated by scripts/ablation_random_flip.py) and produces
figure_random_flip_ablation.pdf.

If the CSV does not exist, runs the full Monte Carlo ablation first.
"""
import os
import sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib import rcParams

# ── Paths ──────────────────────────────────────────────────────────────
REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CSV_PATH = os.path.join(REPO_ROOT, "results", "ablation_random_flip.csv")
OUT_FIG = os.path.join(REPO_ROOT, "figures", "figure_random_flip_ablation.pdf")

BASE_RATES = {"nlsy97": 0.36, "compas": 0.45}
OVERLAPPING_MODELS = ["gpt-4o-mini", "gpt-4.1-mini", "gemini/gemini-2.5-flash"]
MODEL_DISPLAY = {
    "gpt-4o-mini": "GPT-4o Mini",
    "gpt-4.1-mini": "GPT-4.1 Mini",
    "gemini/gemini-2.5-flash": "Gemini 2.5 Flash",
}

# ── Style (matches existing paper figures) ─────────────────────────────
rcParams.update({
    "font.family": "serif",
    "font.serif": ["Computer Modern Roman", "CMU Serif", "DejaVu Serif"],
    "text.usetex": False,
    "axes.linewidth": 0.6,
    "xtick.major.width": 0.5,
    "ytick.major.width": 0.5,
    "xtick.direction": "out",
    "ytick.direction": "out",
    "axes.spines.top": False,
    "axes.spines.right": False,
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
})

MODEL_COLORS = {
    "gpt-4o-mini": "#1E3A8A",
    "gpt-4.1-mini": "#3B82F6",
    "gemini/gemini-2.5-flash": "#93C5FD",
}


def generate_figure(df: pd.DataFrame):
    """Two-panel line plot: BRD vs. flip rate with debate BRD reference."""
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.0), sharey=True)
    datasets = ["nlsy97", "compas"]
    titles = ["NLSY97", "COMPAS"]

    for ax, dataset, title in zip(axes, datasets, titles):
        base_rate = BASE_RATES[dataset]
        theoretical_min = abs(0.50 - base_rate)

        for model in OVERLAPPING_MODELS:
            sub = df[(df["model"] == model) & (df["dataset"] == dataset)]
            if sub.empty:
                continue
            color = MODEL_COLORS[model]
            label = MODEL_DISPLAY[model]

            ax.plot(
                sub["flip_rate"], sub["mean_brd"],
                color=color, linewidth=1.5, label=label, zorder=3,
            )
            ax.fill_between(
                sub["flip_rate"], sub["brd_ci_lo"], sub["brd_ci_hi"],
                color=color, alpha=0.15, zorder=2,
            )
            d_brd = sub["debate_brd"].iloc[0]
            ax.axhline(
                d_brd, color=color, linestyle="--", linewidth=1.0, alpha=0.8, zorder=2,
            )

        ax.axhline(
            theoretical_min, color="#888888", linestyle=":", linewidth=1.0,
            label=f"Random-flip floor ({theoretical_min:.0%})", zorder=1,
        )

        ax.set_xlabel("Flip rate", fontsize=9)
        ax.set_title(
            f"{title} (base rate {base_rate:.0%})",
            fontsize=10, fontweight="bold", pad=8,
        )
        ax.tick_params(axis="both", labelsize=8)
        ax.grid(axis="y", linewidth=0.3, alpha=0.5, zorder=0)
        ax.set_xlim(0, 0.50)
        ax.set_ylim(0, None)

    axes[0].set_ylabel("Base-Rate Deviation (BRD)", fontsize=9)

    handles = []
    for model in OVERLAPPING_MODELS:
        handles.append(
            Line2D([0], [0], color=MODEL_COLORS[model], linewidth=1.5,
                   label=MODEL_DISPLAY[model])
        )
    handles.append(
        Line2D([0], [0], color="#555555", linestyle="--", linewidth=1.0,
               label="Debate BRD (per model)")
    )
    handles.append(
        Line2D([0], [0], color="#888888", linestyle=":", linewidth=1.0,
               label="Random-flip floor")
    )
    fig.legend(
        handles=handles, loc="upper center", ncol=5, fontsize=8,
        frameon=False, bbox_to_anchor=(0.5, 1.02), columnspacing=1.5,
        handletextpad=0.5,
    )

    plt.tight_layout(rect=[0, 0, 1, 0.92])
    os.makedirs(os.path.dirname(OUT_FIG), exist_ok=True)
    fig.savefig(OUT_FIG, bbox_inches="tight", dpi=300)
    print(f"Saved: {OUT_FIG}")
    plt.close(fig)


def main():
    if not os.path.exists(CSV_PATH):
        print(f"CSV not found: {CSV_PATH}")
        print("Running ablation_random_flip.py first...")
        import subprocess
        subprocess.run(
            [sys.executable, os.path.join(REPO_ROOT, "scripts", "ablation_random_flip.py")],
            check=True,
        )

    df = pd.read_csv(CSV_PATH)
    generate_figure(df)


if __name__ == "__main__":
    main()
